---

# This docker-compose file is required to bind ports and volumes for disposable testing.

version: '3.7'
services:
    api:
        image: '{{ cookiecutter.directory_name }}:dev'
        build:
            target: development_build
            args:
                # This only affects builds, which is why it isn't set to "testing"
                ENV: development
        ports:
            - '8000:8000'
        volumes:
            # We mount the code to ensure that we are testing the latest changes
            - .:/code
        command: pytest --cov=api --cov-config=.coveragerc --cov-report=term --cov-report=html
