---

# Base Docker Compose file.
# This defines the basic environments that are used for both develoment and
# testing. Overrides are explicitly specified in the Makefile for their
# relevant targets.
#
# Many patterns here lifted directly from:
# <https://github.com/wemake-services/wemake-django-template>

version: '3.8'
services:
    api:
        image: "{{ cookiecutter.directory_name }}:dev"
        build:
            context: .
            cache_from:
                - "{{ cookiecutter.directory_name }}:dev"
                - "*"
        restart: unless-stopped
        # env_file populates environment variables at runtime
        env_file: .env
